### ISSUE TITLE
Travis tests failing

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-config#37]
Tests pass locally, but the remote setup doesn't !

woop.

Looks like this

```bash
> server started
Listening on :::8008 (multiserver net plugin)
Error: could not connect to sbot
    at /home/travis/build/ssbc/ssb-config/node_modules/ssb-client/index.js:100:23
    at /home/travis/build/ssbc/ssb-config/node_modules/multiserver/compose.js:66:24
    at Socket.<anonymous> (/home/travis/build/ssbc/ssb-config/node_modules/multiserver/plugins/net.js:42:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
  Error: connect EADDRNOTAVAIL :::8008 - Local (:::0)
    at internalConnect (net.js:964:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)
    at net.js:1062:9
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by christianbundy** [comment]
Is this because we're using `::` rather than binding to `127.0.0.1`? I saw a note in the comments that said something like "we're just using IPv4 because IPv6 breaks Travis" or something, but it looks like we've switched to IPv6 by default. Or maybe I'm misreading it?

**Comment by mixmix** [comment]
Yeah I think we need to check if we're in an ipv4/6 env then chose the
default?
I think Windows needs 127.0.0.1 as well even in ipv6... Just another
complication

**Comment by dominictarr** [comment]
I saw the heading and immediately thought ipv6, obviously.
